export const ShippingPlaceHolder = {
  destiny: {
    address: {
      city: 'AYSEN',
      commune: {
        base_name: 'Coyhaique',
        name: 'Aysén',
        code: '11201',
        base_post: 'GXQ',
        zone: 'EXTREMO SUR',
        location_code: 'WPA',
      },
      complement: '',
      country: 'Chile',
      depto: '',
      geolocation: {
        latitude: -45.39962,
        longitude: -72.682803,
      },
      office: '',
      reference: '',
      region: {
        name: 'Región de Aisén del Gral. Carlos Ibañez del Campo',
        region_number: 'XI',
        region_iso_3166: 'CL-AI',
        country: 152,
      },
      street: 'Sargento Aldea',
      street_number: '1845',
    },
    agency_id: '8573',
    agency_name: 'Punto Blue Express Caja Vecina Pablito',
    isPickup: true,
  },
  package: {
    content: 'Pelota',
    dangerous_merchandise: true,
    package_sizes: {
      length: 26,
      height: 16,
      width: 16,
      weight: 3,
    },
    shipping_service: {
      codeDestination: 'WPA',
      codeOrigin: 'CCL',
      price: 2689,
      service: 'STANDARD',
      sla: 2,
      weight: 3,
    },
    size: 'S',
    tax: 511,
    total_value: 3200,
    warranty: false,
    warranty_bill_number: '',
    warranty_extended: 0,
    warranty_value: 1000,
    promotion_id: '',
  },
  receiver: {
    name: 'Aldo',
    lastName: 'Altamira',
    email: 'aldo.altamira2@gmail.com',
    phone: '981234567',
    rut: '161234567',
  },
  save_frequent_client: false,
  save_frequent_package: false,
  save_refund_address: false,
  origin: {
    address: {
      city: 'COCHRANE',
      commune: {
        base_name: 'Coyhaique',
        name: 'Cochrane',
        code: '11301',
        base_post: 'GXQ',
        zone: 'EXTREMO SUR',
        location_code: 'CCL',
      },
      complement: '',
      country: 'Chile',
      depto: '',
      geolocation: {
        latitude: -47.2516701,
        longitude: -72.5610491,
      },
      office: '',
      reference: '',
      region: {
        name: 'Región de Aisén del Gral. Carlos Ibañez del Campo',
        region_number: 'XI',
        region_iso_3166: 'CL-AI',
        country: 152,
      },
      street: 'LAS BANDURRIAS',
      street_number: '100',
    },
    agency_id: '4961',
    agency_name: 'Punto Blue Express Minimarket Patty',
    isPickup: true,
  },
  refund: {
    address: {
      city: 'Quillota',
      commune: {
        base_name: 'La Calera',
        base_post: 'ZLC',
        code: '5501',
        location_code: 'QTA',
        name: 'Quillota',
        zone: 'CENTRO',
      },
      complement: '',
      country: 'Chile',
      depto: '301',
      geolocation: {
        latitude: -32.8819206,
        longitude: -71.2457738,
      },
      office: '',
      reference: '',
      region: {
        name: 'Región de Valparaíso',
        region_iso_3166: 'CL-VS',
        country: 152,
        region_number: 'V',
      },
      street: 'Pudeto',
      street_number: '207',
    },
    agency_id: '',
    agency_name: '',
    isPickup: false,
  },
  save_frequent_origin: false,
};
