const BLUE_BILLING_ADDRESS = 'Av.El Retiro';
const BLUE_BILLING_ADDRESS_NUMBER = '9800';
const BLUE_BILLING_CITY_NAME = 'SANTIAGO';
const BLUE_BILLING_RUT = '96938840-5';
const BLUE_BILLING_POSTAL_CODE = '7556000';
const BLUE_BILLING_LEGACY_ID = 'BLUESUPERAPP';
const BLUE_BILLING_CONTACT_NAME = 'BLUESUPERAPP';
const BLUE_BILLING_PHONE = '97658515';
const BLUE_BILLING_EMAIL = 'BLUESUPER@BX.CL';
const BLUE_BILLING_COMMUNE_BASE_POST = 'SCL';
const BLUE_BILLING_COMMUNE_CODE = '13124';
const BLUE_BILLING_COMMUNE_NAME = 'PUDAHUEL';
const BLUE_BILLING_COMMUNE_COUNTRY = '152';
const BLUE_BILLING_COMMUNE_REGION = 'CL-RM';
const BLUE_BILLING_REGION_COUNTRY = '152';
const BLUE_BILLING_REGION_NAME = 'Región Metropolitana';
const BLUE_BILLING_REGION_ISO = 'CL-RM';
const BLUE_BILLING_REGION_NUMBER = '13';

const BLUE_BILLING = {
  address: BLUE_BILLING_ADDRESS,
  address_number: BLUE_BILLING_ADDRESS_NUMBER,
  city_name: BLUE_BILLING_CITY_NAME,
  rut: BLUE_BILLING_RUT,
  postal_code: BLUE_BILLING_POSTAL_CODE,
  legacy_id: BLUE_BILLING_LEGACY_ID,
  contact_name: BLUE_BILLING_CONTACT_NAME,
  phone: BLUE_BILLING_PHONE,
  email: BLUE_BILLING_EMAIL,
  commune: {
    base_post: BLUE_BILLING_COMMUNE_BASE_POST,
    code: BLUE_BILLING_COMMUNE_CODE,
    name: BLUE_BILLING_COMMUNE_NAME,
    country: BLUE_BILLING_COMMUNE_COUNTRY,
    region: BLUE_BILLING_COMMUNE_REGION,
  },
  region: {
    country: BLUE_BILLING_REGION_COUNTRY,
    name: BLUE_BILLING_REGION_NAME,
    region_iso_3166: BLUE_BILLING_REGION_ISO,
    region_number: BLUE_BILLING_REGION_NUMBER,
  },
};

export default BLUE_BILLING;
